/* Generated by :claw at 2023-10-16T16:53:09.927797Z */

#if defined(__cplusplus)
#include <new>
#endif



#include "llama.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif


__CLAW_API struct llama_timings* __claw_llama_get_timings(struct llama_timings* __claw_result_, struct llama_context* ctx) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:720:36
(*__claw_result_) = llama_get_timings(ctx);
return __claw_result_;
}

__CLAW_API struct llama_model_params* __claw_cE3AE40FE40llama_model_default_params(struct llama_model_params* __claw_result_) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:244:41
(*__claw_result_) = llama_model_default_params();
return __claw_result_;
}

__CLAW_API int __claw_llama_decode(struct llama_context* ctx, struct llama_batch* batch) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:466:19
return llama_decode(ctx, *batch);
}

__CLAW_API void __claw_llama_batch_free(struct llama_batch* batch) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:460:20
llama_batch_free(*batch);
}

__CLAW_API struct llama_model_quantize_params* __claw_cE3AE40FE40llama_model_quantize_default_params(struct llama_model_quantize_params* __claw_result_) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:246:50
(*__claw_result_) = llama_model_quantize_default_params();
return __claw_result_;
}

__CLAW_API struct llama_model* __claw_llama_load_model_from_file(const char* path_model, struct llama_model_params* params) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:256:36
return (struct llama_model*) llama_load_model_from_file(path_model, *params);
}

__CLAW_API struct llama_batch* __claw_llama_batch_get_one(struct llama_batch* __claw_result_, llama_token* tokens, int32_t n_tokens, llama_pos pos_0, llama_seq_id seq_id) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:443:34
(*__claw_result_) = llama_batch_get_one(tokens, n_tokens, pos_0, seq_id);
return __claw_result_;
}

__CLAW_API struct llama_batch* __claw_llama_batch_init(struct llama_batch* __claw_result_, int32_t n_tokens, int32_t embd) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:455:34
(*__claw_result_) = llama_batch_init(n_tokens, embd);
return __claw_result_;
}

__CLAW_API struct llama_context* __claw_llama_new_context_with_model(struct llama_model* model, struct llama_context_params* params) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:262:38
return (struct llama_context*) llama_new_context_with_model(model, *params);
}

__CLAW_API struct llama_context_params* __claw_cE3AE40FE40llama_context_default_params(struct llama_context_params* __claw_result_) {
// /home/aragaer/Projects/claw-llama-cpp/src/lib/llama.cpp/llama.h:245:43
(*__claw_result_) = llama_context_default_params();
return __claw_result_;
}

#if defined(__cplusplus)
}
#endif
